import java.util.*
import kotlin.collections.ArrayList

class Word internal constructor(var word: String, var translate: String, var link: String) {

    companion object {
        val instances = setOf<Word>(
                Word("seism,seimo", "seism地震", "http://etymon.cn/yingyucigen/3093.html"),
                Word("radi-,-ray-,-radio-", "ray,beam光线", "http://etymon.cn/yingyucigen/1082.html"),
                Word("ac,acr,acid", "sour酸的sharp锐利的", "http://etymon.cn/yingyucigen/1121.html"),
                Word("paleo,pale,palae", "old老/旧的", "http://etymon.cn/yingyucigen/2489.html"),
                Word("gubern,govern", "govern管理,统治", "http://etymon.cn/yingyucigen/3092.html"),
                Word("esti,este", "value价值(估计)", "http://etymon.cn/yingyucigen/3091.html"),
                Word("colon", "inhabit栖息", "http://etymon.cn/yingyucigen/3090.html"),
                Word("advance,advant", "before/in front of前,向前", "http://etymon.cn/yingyucigen/3089.html"),
                Word("archea,archa", "ancient,primitive古代/原始的", "http://etymon.cn/yingyucigen/2357.html"),
                Word("athl", "contest竞赛", "http://etymon.cn/yingyucigen/3088.html"),
                Word("all,allo", "other,different异", "http://etymon.cn/yingyucigen/3087.html"),
                Word("nucle,nucl,nucleo", "kernel核", "http://etymon.cn/yingyucigen/3086.html"),
                Word("selen,seleno,seleni", "moon月亮", "http://etymon.cn/yingyucigen/3085.html"),
                Word("nigr,nigri,negro,negr", "black黑", "http://etymon.cn/yingyucigen/3084.html"),
                Word("phob,phobia", "dislike,fear厌恶,怕", "http://etymon.cn/yingyucigen/3083.html"),
                Word("contra,counter,contro", "against反对", "http://etymon.cn/yingyucigen/3082.html"),
                Word("add", "to put to加上", "http://etymon.cn/yingyucigen/3081.html"),
                Word("-s-", "be在", "http://etymon.cn/yingyucigen/3080.html"),
                Word("freeze,frig,friger", "cold冷的", "http://etymon.cn/yingyucigen/3079.html"),
                Word("dyn,dynamo,dynam", "power/ability力,力量", "http://etymon.cn/yingyucigen/3078.html"),
                Word("arch,archy", "government,to rule统治", "http://etymon.cn/yingyucigen/2158.html"),
                Word("gyn,gynec,gyneco", "women,female妇女", "http://etymon.cn/yingyucigen/3077.html"),
                Word("hipp,hippo", "horse马", "http://etymon.cn/yingyucigen/3076.html"),
                Word("dec,decor", "fit,elegance合适", "http://etymon.cn/yingyucigen/3075.html"),
                Word("cyte,cyt,cyto", "cell细胞", "http://etymon.cn/yingyucigen/3074.html"),
                Word("civ,civil", "citizen公民", "http://etymon.cn/yingyucigen/3073.html"),
                Word("ante,anti,ant", "before前", "http://etymon.cn/yingyucigen/3072.html"),
                Word("ump", "to bulge隆起", "http://etymon.cn/yingyucigen/3071.html"),
                Word("brev,brevi,brief,bridg", "short短的", "http://etymon.cn/yingyucigen/1122.html"),
                Word("brig", "hit打,战斗(劫掠)", "http://etymon.cn/yingyucigen/3070.html"),
                Word("biblio,,bibli", "book书", "http://etymon.cn/yingyucigen/3069.html"),
                Word("inter,integr", "整,全", "http://etymon.cn/yingyucigen/3068.html"),
                Word("ign", "火", "http://etymon.cn/yingyucigen/3067.html"),
                Word("helic,helico", "spiral螺旋", "http://etymon.cn/yingyucigen/3066.html"),
                Word("hal", "呼吸", "http://etymon.cn/yingyucigen/3065.html"),
                Word("sel,sul,sult", "summon召集", "http://etymon.cn/yingyucigen/3064.html"),
                Word("corp,corpor", "body身体", "http://etymon.cn/yingyucigen/1072.html"),
                Word("rac", "race种族", "http://etymon.cn/yingyucigen/3063.html"),
                Word("rol", "ring,circle圆,环,滚动", "http://etymon.cn/yingyucigen/3062.html"),
                Word("du,dupl", "two二", "http://etymon.cn/yingyucigen/3061.html"),
                Word("ev", "time,age年龄,寿命,时期", "http://etymon.cn/yingyucigen/1124.html"),
                Word("dextr,dextro,dextra,dexter", "right右", "http://etymon.cn/yingyucigen/1049.html"),
                Word("gran,grain", "seed谷粒,种子", "http://etymon.cn/yingyucigen/1869.html"),
                Word("parl", "说话", "http://etymon.cn/yingyucigen/3060.html"),
                Word("past", "喂养,牧羊人", "http://etymon.cn/yingyucigen/3059.html"),
                Word("ed,es", "to eat吃", "http://etymon.cn/yingyucigen/1812.html"),
                Word("vor", "to eat吃", "http://etymon.cn/yingyucigen/1050.html"),
                Word("phag", "to eat吃", "http://etymon.cn/yingyucigen/3058.html"),
                Word("tuit,tut", "look after,protect照管,监护", "http://etymon.cn/yingyucigen/3057.html"),
                Word("vol,volunt", "will,free意志,意愿,自由", "http://etymon.cn/yingyucigen/1816.html"),
                Word("temper", "moderate,mix,strecth节制,调节,混合", "http://etymon.cn/yingyucigen/1826.html"),
                Word("crim,crimin", "separate分开", "http://etymon.cn/yingyucigen/3056.html"),
                Word("crim,crimin,crimine", "crime,guilty,accusation控诉,罪行", "http://etymon.cn/yingyucigen/1855.html"),
                Word("tric,trig", "trifle琐碎", "http://etymon.cn/yingyucigen/1870.html"),
                Word("spon,spond,spons,spous", "to promise承诺", "http://etymon.cn/yingyucigen/1982.html"),
                Word("fisc", "chest,money basket,treasury国库", "http://etymon.cn/yingyucigen/2029.html"),
                Word("cogn,gno(gn,n),cognis,gnos", "to know知道", "http://etymon.cn/yingyucigen/2144.html"),
                Word("car,carn", "flesh肉", "http://etymon.cn/yingyucigen/1128.html"),
                Word("ver", "to feel awe,to fear敬畏,尊敬", "http://etymon.cn/yingyucigen/1845.html"),
                Word("sua,suad,suas(suav)", "to persuade,to advise劝告", "http://etymon.cn/yingyucigen/1930.html"),
                Word("plaud,plaus(plod,plos,plex)", "strike打击clap鼓掌", "http://etymon.cn/yingyucigen/1107.html"),
                Word("plant", "plant,to plant植物,种植", "http://etymon.cn/yingyucigen/1441.html"),
                Word("pel,puls(peal)", "to drive驱散,驱使", "http://etymon.cn/yingyucigen/1929.html"),
                Word("loqu,locut", "to say,to speak说话", "http://etymon.cn/yingyucigen/1808.html"),
                Word("imit", "copy,imitate模仿", "http://etymon.cn/yingyucigen/1106.html"),
                Word("ut,uti,util,us", "to use使用", "http://etymon.cn/yingyucigen/1925.html"),
                Word("tent,tempt,emp,temp", "to try尝试,to touch触摸", "http://etymon.cn/yingyucigen/3055.html"),
                Word("sort", "kind种类", "http://etymon.cn/yingyucigen/3054.html"),
                Word("soph", "wise,wisdom智慧", "http://etymon.cn/yingyucigen/3053.html"),
                Word("rot", "revolve,wheel,turn转,轮子", "http://etymon.cn/yingyucigen/3052.html"),
                Word("rept", "to creep爬行,蔓延", "http://etymon.cn/yingyucigen/3051.html"),
                Word("quit", "free,release自由,释放,免除", "http://etymon.cn/yingyucigen/3050.html"),
                Word("quer,quar", "to complain抱怨", "http://etymon.cn/yingyucigen/3049.html"),
                Word("plain,plaint", "beat打,to beat the breast捶胸", "http://etymon.cn/yingyucigen/3048.html"),
                Word("port", "gate门", "http://etymon.cn/yingyucigen/3047.html"),
                Word("pur", "pure纯洁", "http://etymon.cn/yingyucigen/3046.html"),
                Word("purg", "clean清洁,干净", "http://etymon.cn/yingyucigen/1877.html"),
                Word("port,portat", "to carry搬运", "http://etymon.cn/yingyucigen/1841.html"),
                Word("port", "分", "http://etymon.cn/yingyucigen/2288.html"),
                Word("ortho", "straight直的,right正的", "http://etymon.cn/yingyucigen/3045.html"),
                Word("phil,philo", "loving爱", "http://etymon.cn/yingyucigen/3044.html"),
                Word("nul,null", "nothing无", "http://etymon.cn/yingyucigen/3043.html"),
                Word("nau,nav,naut,naus", "ship,boat船", "http://etymon.cn/yingyucigen/3042.html"),
                Word("mechan", "mechine机器", "http://etymon.cn/yingyucigen/3041.html"),
                Word("mark,marg,march", "to mark做记号,boundary边界", "http://etymon.cn/yingyucigen/3040.html"),
                Word("loc,loco", "location,place位置,地方", "http://etymon.cn/yingyucigen/3039.html"),
                Word("libr,lib", "book书籍", "http://etymon.cn/yingyucigen/3038.html"),
                Word("idio,idi", "personal,distinct", "http://etymon.cn/yingyucigen/3037.html"),
                Word("herb", "grass草", "http://etymon.cn/yingyucigen/3036.html"),
                Word("hap", "luck运气,机会", "http://etymon.cn/yingyucigen/3035.html"),
                Word("greg", "flock,gather,mob群,聚结", "http://etymon.cn/yingyucigen/1878.html"),
                Word("gam,gamo", "marry,marriage婚姻", "http://etymon.cn/yingyucigen/3034.html"),
                Word("fug,bow,bog", "flee逃,弯", "http://etymon.cn/yingyucigen/3033.html"),
                Word("fund,found,fus", "melt,pour融化,倾倒,浇筑", "http://etymon.cn/yingyucigen/3032.html"),
                Word("son", "sound声音", "http://etymon.cn/yingyucigen/3031.html"),
                Word("mor", "custom风俗,习惯,道德", "http://etymon.cn/yingyucigen/3030.html"),
                Word("par", "to bear,to give,birth to", "http://etymon.cn/yingyucigen/3029.html"),
                Word("flex,flect", "bend弯曲", "http://etymon.cn/yingyucigen/3028.html"),
                Word("torn,tour,tourn", "turn转动", "http://etymon.cn/yingyucigen/3027.html"),
                Word("ton,tun", "sound,tone声,音调", "http://etymon.cn/yingyucigen/3026.html"),
                Word("the,theo", "god神", "http://etymon.cn/yingyucigen/3025.html"),
                Word("fest", "festival节日,祝宴", "http://etymon.cn/yingyucigen/3024.html"),
                Word("electr", "amber,electricity琥珀,电", "http://etymon.cn/yingyucigen/3023.html"),
                Word("ego", "I,self我,自己", "http://etymon.cn/yingyucigen/3022.html"),
                Word("eco(ecu,oce)", "house家", "http://etymon.cn/yingyucigen/1056.html"),
                Word("dom", "house家", "http://etymon.cn/yingyucigen/3021.html"),
                Word("dom", "to tame驯服,to rule统治", "http://etymon.cn/yingyucigen/3020.html"),
                Word("dei,divin", "god神", "http://etymon.cn/yingyucigen/3019.html"),
                Word("deb,du", "to owe负债", "http://etymon.cn/yingyucigen/3018.html"),
                Word("vuls,vulse", "to pluck采,摘,拉", "http://etymon.cn/yingyucigen/3017.html"),
                Word("vil,vuln,vul,vuls,vult", "pluck,,tear撕,扯,野蛮", "http://etymon.cn/yingyucigen/3016.html"),
                Word("urb", "city城市", "http://etymon.cn/yingyucigen/3015.html"),
                Word("hous,hus,hid,hut", "盖,藏", "http://etymon.cn/yingyucigen/3014.html"),
                Word("count", "to count计算", "http://etymon.cn/yingyucigen/3013.html"),
                Word("cover", "cover覆盖", "http://etymon.cn/yingyucigen/3012.html"),
                Word("chron", "time时间", "http://etymon.cn/yingyucigen/3011.html"),
                Word("aqua,aqu,aque,aqui", "water水", "http://etymon.cn/yingyucigen/3010.html"),
                Word("cosm", "秩序,宇宙,装饰", "http://etymon.cn/yingyucigen/3009.html"),
                Word("aer,air,er,ar", "air空气", "http://etymon.cn/yingyucigen/3008.html"),
                Word("joy,joc,jol,jov", "欢乐,开心", "http://etymon.cn/yingyucigen/3007.html"),
                Word("ang,eng,ank,anch", "弯曲,角", "http://etymon.cn/yingyucigen/3006.html"),
                Word("ang", "to strangle勒死", "http://etymon.cn/yingyucigen/3005.html"),
                Word("angul,angl", "corner,angle", "http://etymon.cn/yingyucigen/3004.html"),
                Word("crit,cris", "to judge评判,区分", "http://etymon.cn/yingyucigen/3003.html"),
                Word("sen", "old老的,年长的", "http://etymon.cn/yingyucigen/3002.html"),
                Word("nutr,nurt,nutri", "to nourish营养", "http://etymon.cn/yingyucigen/1815.html"),
                Word("dent", "tooth牙齿", "http://etymon.cn/yingyucigen/3001.html"),
                Word("dem", "people人民", "http://etymon.cn/yingyucigen/3000.html"),
                Word("draw", "拉,牵引(前缀)", "http://etymon.cn/yingyucigen/2999.html"),
                Word("habit,hibit", "have,hold,dwell拥有,占据,居住", "http://etymon.cn/yingyucigen/2998.html"),
                Word("sumpt,sum", "to take,to use,to waste", "http://etymon.cn/yingyucigen/1779.html"),
                Word("empt,em(eem,mpt,m,anson),ampl", "to take,buy", "http://etymon.cn/yingyucigen/1884.html"),
                Word("op,oper,of", "to work,riches", "http://etymon.cn/yingyucigen/1074.html"),
                Word("ped(pod,pus,peach,patch,pet)", "foot足", "http://etymon.cn/yingyucigen/1856.html"),
                Word("ped", "child儿童", "http://etymon.cn/yingyucigen/2997.html"),
                Word("or,ora,ore,orat", "to say", "http://etymon.cn/yingyucigen/1823.html"),
                Word("osteo,oss(e)", "bone骨头", "http://etymon.cn/yingyucigen/2485.html"),
                Word("fac,fact,fec,fect,fic,fict(feas,feit,feat,fit)", "do,make做", "http://etymon.cn/yingyucigen/2180.html"),
                Word("ducc,duc,duct(du)", "to lead引导", "http://etymon.cn/yingyucigen/2204.html"),
                Word("dign(dain,deign)", "worthy有价值的", "http://etymon.cn/yingyucigen/2006.html"),
                Word("xyl(o)", "wood木", "http://etymon.cn/yingyucigen/2559.html"),
                Word("gen(gn),gener,gent", "birth出生,race种族", "http://etymon.cn/yingyucigen/2128.html"),
                Word("oxy(ox)", "sharp,acid酸", "http://etymon.cn/yingyucigen/1802.html"),
                Word("gon", "to compare,to test,angle", "http://etymon.cn/yingyucigen/1800.html"),
                Word("rat,ratio", "to reckon推定,reason理由", "http://etymon.cn/yingyucigen/843.html"),
                Word("zo(o)", "life/animal生命/动物", "http://etymon.cn/yingyucigen/2558.html"),
                Word("xer(o)", "dry干燥", "http://etymon.cn/yingyucigen/2557.html"),
                Word("vibr", "to shake摇动", "http://etymon.cn/yingyucigen/2556.html"),
                Word("vigil", "醒着", "http://etymon.cn/yingyucigen/2555.html"),
                Word("vigor", "精力", "http://etymon.cn/yingyucigen/2554.html"),
                Word("viol", "violence/strangth暴力/力量", "http://etymon.cn/yingyucigen/2553.html"),
                Word("xanth,xantho", "yellow黄", "http://etymon.cn/yingyucigen/2552.html"),
                Word("verd,vir", "绿", "http://etymon.cn/yingyucigen/2551.html"),
                Word("verm(i)", "蠕虫", "http://etymon.cn/yingyucigen/2550.html"),
                Word("vent", "wind风", "http://etymon.cn/yingyucigen/2549.html"),
                Word("vend", "卖", "http://etymon.cn/yingyucigen/2548.html"),
                Word("velop", "包,卷,裹", "http://etymon.cn/yingyucigen/2547.html"),
                Word("veget", "植物", "http://etymon.cn/yingyucigen/2546.html"),
                Word("van", "前,先", "http://etymon.cn/yingyucigen/2545.html"),
                Word("urg(y)", "制作", "http://etymon.cn/yingyucigen/2544.html"),
                Word("vacc", "牛", "http://etymon.cn/yingyucigen/2543.html"),
                Word("ur", "urine尿", "http://etymon.cn/yingyucigen/2542.html"),
                Word("trop", "turn转", "http://etymon.cn/yingyucigen/2541.html"),
                Word("tox", "poison毒", "http://etymon.cn/yingyucigen/2540.html"),
                Word("top", "地方", "http://etymon.cn/yingyucigen/2539.html"),
                Word("toler", "endure容忍", "http://etymon.cn/yingyucigen/2538.html"),
                Word("tir", "拉,引", "http://etymon.cn/yingyucigen/2537.html"),
                Word("therm(o)", "hot/heat热/热的", "http://etymon.cn/yingyucigen/2536.html"),
                Word("terg,ters", "擦,除掉", "http://etymon.cn/yingyucigen/2535.html"),
                Word("sum", "总,最高", "http://etymon.cn/yingyucigen/2534.html"),
                Word("techo,techn(o)", "art/skill技艺/技术", "http://etymon.cn/yingyucigen/2533.html"),
                Word("stru,stro,struct", "build建造", "http://etymon.cn/yingyucigen/2532.html"),
                Word("strat", "层", "http://etymon.cn/yingyucigen/2531.html"),
                Word("stor", "存放", "http://etymon.cn/yingyucigen/2530.html"),
                Word("stom,stomat(o)", "mouth口", "http://etymon.cn/yingyucigen/2529.html"),
                Word("stereo", "solid立体", "http://etymon.cn/yingyucigen/2528.html"),
                Word("sorb,sorpt", "吸", "http://etymon.cn/yingyucigen/2527.html"),
                Word("soci", "companion,asscoiate同伴,结交,联合", "http://etymon.cn/yingyucigen/2526.html"),
                Word("Sino,Sinic(o)", "China中国", "http://etymon.cn/yingyucigen/2525.html"),
                Word("serv", "to serve服务,to keep保持", "http://etymon.cn/yingyucigen/2073.html"),
                Word("serv", "watch注视", "http://etymon.cn/yingyucigen/2524.html"),
                Word("seri", "系列,连", "http://etymon.cn/yingyucigen/2523.html"),
                Word("scop", "观察,镜", "http://etymon.cn/yingyucigen/2522.html"),
                Word("scler(o)", "硬", "http://etymon.cn/yingyucigen/2521.html"),
                Word("sanguin,sangui", "blood血", "http://etymon.cn/yingyucigen/2520.html"),
                Word("sarc(o)", "flesh肉", "http://etymon.cn/yingyucigen/2519.html"),
                Word("san,sal,sanit", "健康,卫生", "http://etymon.cn/yingyucigen/2518.html"),
                Word("rhag,rrhag,rrhea", "(过多)流出,破裂", "http://etymon.cn/yingyucigen/2517.html"),
                Word("riv", "flow/brook/river流动,河", "http://etymon.cn/yingyucigen/2516.html"),
                Word("rhin(o)", "nose鼻", "http://etymon.cn/yingyucigen/2515.html"),
                Word("rhiz(o)", "root根", "http://etymon.cn/yingyucigen/2514.html"),
                Word("pyr(o)", "fire火", "http://etymon.cn/yingyucigen/2513.html"),
                Word("pter", "wing翅,翼", "http://etymon.cn/yingyucigen/2512.html"),
                Word("petr,petro", "stone石,rock岩石", "http://etymon.cn/yingyucigen/2511.html"),
                Word("psych(o)", "soul,mind灵魂,精神,心理", "http://etymon.cn/yingyucigen/2510.html"),
                Word("potam", "河", "http://etymon.cn/yingyucigen/2509.html"),
                Word("priv", "个人,私自", "http://etymon.cn/yingyucigen/2508.html"),
                Word("proto,prot", "rude/original/primitive前,第一,原", "http://etymon.cn/yingyucigen/2507.html"),
                Word("proxim,proach", "near接近", "http://etymon.cn/yingyucigen/2506.html"),
                Word("pot", "饮", "http://etymon.cn/yingyucigen/2505.html"),
                Word("potent,pot", "power/ability力量/能力", "http://etymon.cn/yingyucigen/2504.html"),
                Word("porc,prok", "猪", "http://etymon.cn/yingyucigen/2503.html"),
                Word("pol(y)", "卖", "http://etymon.cn/yingyucigen/2502.html"),
                Word("plut(o)", "money财", "http://etymon.cn/yingyucigen/2501.html"),
                Word("plur,plus", "多", "http://etymon.cn/yingyucigen/2500.html"),
                Word("phot(o),phos", "light光", "http://etymon.cn/yingyucigen/2494.html"),
                Word("pisc", "fish鱼", "http://etymon.cn/yingyucigen/2499.html"),
                Word("phyt(o)", "plant植物", "http://etymon.cn/yingyucigen/2498.html"),
                Word("phyll(o)", "leaf叶", "http://etymon.cn/yingyucigen/2497.html"),
                Word("phor", "带,持有,具有", "http://etymon.cn/yingyucigen/2495.html"),
                Word("phem,phet", "言", "http://etymon.cn/yingyucigen/2493.html"),
                Word("peps,pept", "peptic消化的", "http://etymon.cn/yingyucigen/2492.html"),
                Word("pen,penn,pinn", "feathers羽毛", "http://etymon.cn/yingyucigen/2491.html"),
                Word("reg(reig)", "to rule统治,king王,规则", "http://etymon.cn/yingyucigen/1098.html"),
                Word("par(pair,per,pir,peer)", "equal平等,相等,准备", "http://etymon.cn/yingyucigen/2314.html"),
                Word("pand,pans", "展开", "http://etymon.cn/yingyucigen/2490.html"),
                Word("oste(o)", "骨", "http://etymon.cn/yingyucigen/2488.html"),
                Word("ornith", "bird鸟", "http://etymon.cn/yingyucigen/2487.html"),
                Word("ot(o)", "ear耳", "http://etymon.cn/yingyucigen/2486.html"),
                Word("oram,orama", "view观看,景", "http://etymon.cn/yingyucigen/2484.html"),
                Word("optim", "最好的", "http://etymon.cn/yingyucigen/2483.html"),
                Word("ophi(o)", "蛇", "http://etymon.cn/yingyucigen/2482.html"),
                Word("opt", "to choose选,to wish希望", "http://etymon.cn/yingyucigen/2481.html"),
                Word("oo", "egg卵", "http://etymon.cn/yingyucigen/2479.html"),
                Word("ov(i)", "卵", "http://etymon.cn/yingyucigen/2480.html"),
                Word("olig,oligo", "few少", "http://etymon.cn/yingyucigen/2478.html"),
                Word("ole(o)", "油", "http://etymon.cn/yingyucigen/2477.html"),
                Word("odont(o)", "tooth牙齿.牙", "http://etymon.cn/yingyucigen/2476.html"),
                Word("nour,nurs", "喂养,营养", "http://etymon.cn/yingyucigen/2475.html"),
                Word("od", "路", "http://etymon.cn/yingyucigen/2474.html"),
                Word("ocul", "eye/bud眼睛/苗", "http://etymon.cn/yingyucigen/2473.html"),
                Word("nom(y)", "学,术,法,治", "http://etymon.cn/yingyucigen/2472.html"),
                Word("neutr", "中", "http://etymon.cn/yingyucigen/2471.html"),
                Word("neg", "否认,否定", "http://etymon.cn/yingyucigen/2470.html"),
                Word("necr(o)", "death死亡,deadbody死尸", "http://etymon.cn/yingyucigen/2469.html"),
                Word("myst", "secret/mystery秘密/神秘", "http://etymon.cn/yingyucigen/2468.html"),
                Word("nat", "浮游", "http://etymon.cn/yingyucigen/2467.html"),
                Word("nat,nasc(naiss,naiv)", "to be born出生", "http://etymon.cn/yingyucigen/1822.html"),
                Word("mund", "世界", "http://etymon.cn/yingyucigen/2466.html"),
                Word("mis,mixt,mix", "mix混杂,混合", "http://etymon.cn/yingyucigen/2465.html"),
                Word("micr,micro", "微", "http://etymon.cn/yingyucigen/2464.html"),
                Word("mes(o)", "middle中间", "http://etymon.cn/yingyucigen/2463.html"),
                Word("melan", "black黑色", "http://etymon.cn/yingyucigen/2462.html"),
                Word("mancy", "divination占卜", "http://etymon.cn/yingyucigen/2461.html"),
                Word("men,min", "威胁", "http://etymon.cn/yingyucigen/2460.html"),
                Word("lapid", "stone石头", "http://etymon.cn/yingyucigen/2447.html"),
                Word("mamm", "breast奈子", "http://etymon.cn/yingyucigen/2459.html"),
                Word("macr,macro", "great大的", "http://etymon.cn/yingyucigen/2458.html"),
                Word("lys(i),lyt", "分,解,融,散", "http://etymon.cn/yingyucigen/2457.html"),
                Word("luc(lux,lus),lust,lustr", "light,bright明亮的", "http://etymon.cn/yingyucigen/1883.html"),
                Word("liqu", "液体", "http://etymon.cn/yingyucigen/2456.html"),
                Word("lith,lite,lithic,litho", "stone石", "http://etymon.cn/yingyucigen/1055.html"),
                Word("liber,liver", "free自由的", "http://etymon.cn/yingyucigen/2455.html"),
                Word("gnor,gnos,gniz", "知", "http://etymon.cn/yingyucigen/2423.html"),
                Word("lic", "to entice,to permit准许", "http://etymon.cn/yingyucigen/1879.html"),
                Word("liber,libr,liter,lev(el)", "天平,秤,称", "http://etymon.cn/yingyucigen/2454.html"),
                Word("leuc", "white白", "http://etymon.cn/yingyucigen/2453.html"),
                Word("lect", "言", "http://etymon.cn/yingyucigen/2452.html"),
                Word("lax,lyse", "松弛", "http://etymon.cn/yingyucigen/2451.html"),
                Word("latr(y),later", "serve,worship崇拜,崇拜者", "http://etymon.cn/yingyucigen/2450.html"),
                Word("laryngo", "throat咽喉", "http://etymon.cn/yingyucigen/2449.html"),
                Word("laps", "slip,glide滑,溜", "http://etymon.cn/yingyucigen/2448.html"),
                Word("galact,lact", "乳", "http://etymon.cn/yingyucigen/2446.html"),
                Word("lachrym", "泪", "http://etymon.cn/yingyucigen/2445.html"),
                Word("labi", "lip唇", "http://etymon.cn/yingyucigen/2444.html"),
                Word("iter", "再", "http://etymon.cn/yingyucigen/2443.html"),
                Word("iso", "equal,similar相等,相同", "http://etymon.cn/yingyucigen/2439.html"),
                Word("ir,irr", "怒", "http://etymon.cn/yingyucigen/2438.html"),
                Word("iod", "iodine碘", "http://etymon.cn/yingyucigen/2437.html"),
                Word("ident", "相同", "http://etymon.cn/yingyucigen/2436.html"),
                Word("ide,ideo", "idea意,观念", "http://etymon.cn/yingyucigen/2435.html"),
                Word("hypn,hypno", "sleep睡眠", "http://etymon.cn/yingyucigen/2434.html"),
                Word("ichthy", "鱼", "http://etymon.cn/yingyucigen/2433.html"),
                Word("hor", "时间,小时", "http://etymon.cn/yingyucigen/2432.html"),
                Word("horr,hor", "怕", "http://etymon.cn/yingyucigen/2431.html"),
                Word("hydr,hydro,hydric", "水", "http://etymon.cn/yingyucigen/2430.html"),
                Word("homo", "同", "http://etymon.cn/yingyucigen/2429.html"),
                Word("holo", "全", "http://etymon.cn/yingyucigen/2428.html"),
                Word("heter,hetero", "异", "http://etymon.cn/yingyucigen/2427.html"),
                Word("heli.helio", "太阳", "http://etymon.cn/yingyucigen/2426.html"),
                Word("hedron,hedral", "..面体,..面体的", "http://etymon.cn/yingyucigen/2425.html"),
                Word("gyr,gyro", "旋转", "http://etymon.cn/yingyucigen/2424.html"),
                Word("gloss,glot", "tongue舌,语言", "http://etymon.cn/yingyucigen/2422.html"),
                Word("glaci", "冰", "http://etymon.cn/yingyucigen/2421.html"),
                Word("geo", "地", "http://etymon.cn/yingyucigen/2420.html"),
                Word("gastr,gastro", "胃,腹", "http://etymon.cn/yingyucigen/2419.html"),
                Word("fibr", "纤维", "http://etymon.cn/yingyucigen/2418.html"),
                Word("fid,fiss", "break,spilt裂开", "http://etymon.cn/yingyucigen/2417.html"),
                Word("fix", "to fasten固定", "http://etymon.cn/yingyucigen/2416.html"),
                Word("flor(i),flour", "flower花", "http://etymon.cn/yingyucigen/2415.html"),
                Word("foli", "叶", "http://etymon.cn/yingyucigen/2414.html"),
                Word("frater", "brother兄弟", "http://etymon.cn/yingyucigen/2413.html"),
                Word("frug,fruct", "ruit/enjoy水果/享受", "http://etymon.cn/yingyucigen/2412.html"),
                Word("ferr(o)", "iron铁", "http://etymon.cn/yingyucigen/2411.html"),
                Word("fend,fens,fest", "strike打击", "http://etymon.cn/yingyucigen/2410.html"),
                Word("fem,femin", "妇女", "http://etymon.cn/yingyucigen/2409.html"),
                Word("febr(i)", "热", "http://etymon.cn/yingyucigen/2408.html"),
                Word("fasc", "捆,束", "http://etymon.cn/yingyucigen/2407.html"),
                Word("fare", "to go走,行", "http://etymon.cn/yingyucigen/2406.html"),
                Word("fabric", "制造", "http://etymon.cn/yingyucigen/2405.html"),
                Word("enter", "肠", "http://etymon.cn/yingyucigen/2404.html"),
                Word("entom(o)", "昆虫", "http://etymon.cn/yingyucigen/2403.html"),
                Word("erg", "工作", "http://etymon.cn/yingyucigen/2402.html"),
                Word("ethn(o)", "nation,people人种,种族", "http://etymon.cn/yingyucigen/2401.html"),
                Word("emper,imper", "命令", "http://etymon.cn/yingyucigen/2400.html"),
                Word("dors", "背后", "http://etymon.cn/yingyucigen/2399.html"),
                Word("divid,divis", "分", "http://etymon.cn/yingyucigen/2398.html"),
                Word("derm,derma,dermat", "皮", "http://etymon.cn/yingyucigen/2397.html"),
                Word("dens", "密,浓", "http://etymon.cn/yingyucigen/2396.html"),
                Word("dendr(o)", "树", "http://etymon.cn/yingyucigen/2395.html"),
                Word("dactyl(o)", "指.趾", "http://etymon.cn/yingyucigen/2394.html"),
                Word("cyan(o)", "蓝,青,氰", "http://etymon.cn/yingyucigen/2393.html"),
                Word("curv", "弯曲", "http://etymon.cn/yingyucigen/2392.html"),
                Word("crypt,crypto", "隐,神秘,隐藏", "http://etymon.cn/yingyucigen/2391.html"),
                Word("chrom(o),chromat(o)", "色", "http://etymon.cn/yingyucigen/2384.html"),
                Word("clin", "床", "http://etymon.cn/yingyucigen/2386.html"),
                Word("commod", "便利,方便", "http://etymon.cn/yingyucigen/2387.html"),
                Word("corn", "角", "http://etymon.cn/yingyucigen/2388.html"),
                Word("crani(o)", "头颅,头盖", "http://etymon.cn/yingyucigen/2390.html"),
                Word("cry,cryo", "冷,冻", "http://etymon.cn/yingyucigen/2389.html"),
                Word("chrys", "金", "http://etymon.cn/yingyucigen/2385.html"),
                Word("chlor,chloro", "氯,绿", "http://etymon.cn/yingyucigen/2383.html"),
                Word("chiro,cheir", "手", "http://etymon.cn/yingyucigen/2382.html"),
                Word("car,char", "车", "http://etymon.cn/yingyucigen/2381.html"),
                Word("andr(o)", "man,male人,男人,雄性", "http://etymon.cn/yingyucigen/2354.html"),
                Word("anthrop(o)", "man,human人,人类", "http://etymon.cn/yingyucigen/2355.html"),
                Word("bi(o)", "life生命,生物", "http://etymon.cn/yingyucigen/2365.html"),
                Word("blanc", "white白", "http://etymon.cn/yingyucigen/2366.html"),
                Word("calor,cale", "热", "http://etymon.cn/yingyucigen/2370.html"),
                Word("cart,chart", "纸", "http://etymon.cn/yingyucigen/2376.html"),
                Word("cav", "洞,空", "http://etymon.cn/yingyucigen/2377.html"),
                Word("cent(i)", "百,百分之一", "http://etymon.cn/yingyucigen/2378.html"),
                Word("centr", "center中心", "http://etymon.cn/yingyucigen/2379.html"),
                Word("cephal", "head头", "http://etymon.cn/yingyucigen/2380.html"),
                Word("carp,carpo", "果实", "http://etymon.cn/yingyucigen/2375.html"),
                Word("cept,cap,capt,ceiv(ceit,cip,cup)", "to take,to seize拿,抓", "http://etymon.cn/yingyucigen/2139.html"),
                Word("card,cardi", "心,心脏", "http://etymon.cn/yingyucigen/2374.html"),
                Word("cap,capit", "头", "http://etymon.cn/yingyucigen/2373.html"),
                Word("cand,cend,cens", "white白色的,bright光亮的", "http://etymon.cn/yingyucigen/2372.html"),
                Word("camp", "field田地,原野,旷野", "http://etymon.cn/yingyucigen/2371.html"),
                Word("brut", "兽", "http://etymon.cn/yingyucigen/2369.html"),
                Word("cac,caco", "恶", "http://etymon.cn/yingyucigen/2368.html"),
                Word("calc,calcul", "lime,stone,to reckon石灰,石头,计算", "http://etymon.cn/yingyucigen/1868.html"),
                Word("blast,blasto", "germ胚,芽", "http://etymon.cn/yingyucigen/2367.html"),
                Word("beaut", "美", "http://etymon.cn/yingyucigen/2364.html"),
                Word("bar(baro,bary)", "重,压", "http://etymon.cn/yingyucigen/2363.html"),
                Word("barb", "胡须", "http://etymon.cn/yingyucigen/2362.html"),
                Word("aur,auri", "ear耳", "http://etymon.cn/yingyucigen/2361.html"),
                Word("ard,ars", "烧", "http://etymon.cn/yingyucigen/2360.html"),
                Word("art,arthr,arthro", "关节", "http://etymon.cn/yingyucigen/2359.html"),
                Word("arter,arterio,arteri", "动脉", "http://etymon.cn/yingyucigen/2358.html"),
                Word("anth", "flower花", "http://etymon.cn/yingyucigen/2356.html"),
                Word("am,em", "拿", "http://etymon.cn/yingyucigen/2353.html"),
                Word("all", "other", "http://etymon.cn/yingyucigen/1807.html"),
                Word("alg(o)", "痛", "http://etymon.cn/yingyucigen/2352.html"),
                Word("agr(o),agri", "田地", "http://etymon.cn/yingyucigen/2351.html"),
                Word("agogue(agog)", "lead,leader领导,领导者,引领", "http://etymon.cn/yingyucigen/2350.html"),
                Word("aem,haem(o),haemat(o),em,hem(o),hemat(o)", "血", "http://etymon.cn/yingyucigen/2349.html"),
                Word("sid(sed,sit),sess(sid)", "to sit坐", "http://etymon.cn/yingyucigen/2331.html"),
                Word("st,sta,stat,stit,sist,stitut", "to stand站立", "http://etymon.cn/yingyucigen/2348.html"),
                Word("spect,speci,spec(spic,spi,spy)", "to look,to see看", "http://etymon.cn/yingyucigen/2316.html"),
                Word("pend,pens(pond,penc)", "hang悬挂,weigh称重,pay花费", "http://etymon.cn/yingyucigen/2315.html"),
                Word("mod", "fit,manner,modern,measure,kind,way方法,方式", "http://etymon.cn/yingyucigen/2307.html"),
                Word("equ(iqu)", "equal,same相同", "http://etymon.cn/yingyucigen/2313.html"),
                Word("tard", "slow", "http://etymon.cn/yingyucigen/1686.html"),
                Word("cel,celer", "swift快速", "http://etymon.cn/yingyucigen/2312.html"),
                Word("veng,vind,venge", "to punish惩罚,to avenge复仇", "http://etymon.cn/yingyucigen/2311.html"),
                Word("sal", "salt盐", "http://etymon.cn/yingyucigen/2309.html"),
                Word("sal(sul,sil,sail,saul)", "to leap跳", "http://etymon.cn/yingyucigen/2310.html"),
                Word("flu,flux", "to flow流动", "http://etymon.cn/yingyucigen/2308.html"),
                Word("qui,quiet", "to rest休息,clam安静的", "http://etymon.cn/yingyucigen/2306.html"),
                Word("her", "heir继承人", "http://etymon.cn/yingyucigen/1131.html"),
                Word("her,hes", "to stick粘着", "http://etymon.cn/yingyucigen/2305.html"),
                Word("cor,cord(cour)", "heart心", "http://etymon.cn/yingyucigen/2302.html"),
                Word("val(vail)", "worth价值,strong强壮的", "http://etymon.cn/yingyucigen/2301.html"),
                Word("flict", "to stike打击", "http://etymon.cn/yingyucigen/2300.html"),
                Word("lig(li,leag,ly)", "to bind,to tie绑", "http://etymon.cn/yingyucigen/2299.html"),
                Word("claim,clam", "to cry,to shout", "http://etymon.cn/yingyucigen/2298.html"),
                Word("apt(ept,att)", "fit适当的", "http://etymon.cn/yingyucigen/2297.html"),
                Word("lot", "lot", "http://etymon.cn/yingyucigen/2296.html"),
                Word("ne(na,no,n)", "not不", "http://etymon.cn/yingyucigen/2295.html"),
                Word("pac,peas,pact", "peace和平", "http://etymon.cn/yingyucigen/2294.html"),
                Word("plic,ply,pli,ple,plex,plo", "to flod倍,重,折叠", "http://etymon.cn/yingyucigen/2293.html"),
                Word("sert", "to put,to join放置,结合", "http://etymon.cn/yingyucigen/2292.html"),
                Word("ced,cess(ceed,ceas)", "to go走", "http://etymon.cn/yingyucigen/2291.html"),
                Word("nex,nect", "to bind绑,连结", "http://etymon.cn/yingyucigen/2290.html"),
                Word("nihil", "nothing无,虚无", "http://etymon.cn/yingyucigen/2289.html"),
                Word("preci(prais,pric,priz)", "price价格,价值", "http://etymon.cn/yingyucigen/2287.html"),
                Word("spir,spirat", "to breathe呼吸", "http://etymon.cn/yingyucigen/2286.html"),
                Word("grav(griev),gravat", "heavy重,加重", "http://etymon.cn/yingyucigen/2285.html"),
                Word("ven,vent", "to come来", "http://etymon.cn/yingyucigen/2284.html"),
                Word("journ", "day天,日", "http://etymon.cn/yingyucigen/2283.html"),
                Word("clim", "ladder,slope", "http://etymon.cn/yingyucigen/2280.html"),
                Word("sur", "certain确定的,secure安全的", "http://etymon.cn/yingyucigen/2279.html"),
                Word("sem(sembl),sim(simul,simil)","same,like,equal", "http://etymon.cn/yingyucigen/2278.html"),
                Word("pall","pale苍白无力的,暗淡的,浅色的", "http://etymon.cn/yingyucigen/2271.html"),
                Word("lud,lus","to play游戏,扮演", "http://etymon.cn/yingyucigen/2270.html"),
                Word("lev(liev)","to raise举,升,to light轻的", "http://etymon.cn/yingyucigen/2269.html"),
                Word("fil","children,son子女,儿子", "http://etymon.cn/yingyucigen/2268.html"),
                Word("fil","thread线,to spin纺织,foul脏", "http://etymon.cn/yingyucigen/2267.html"),
                Word("ali,al,alter(ulter,altru)","other其他的,变更", "http://etymon.cn/yingyucigen/2266.html"),
                Word("rad,ras(raz)","to rub,to scrape刮擦", "http://etymon.cn/yingyucigen/2258.html"),
                Word("ori(ort)","to rise,to arise升起", "http://etymon.cn/yingyucigen/2257.html"),
                Word("trud,trus","to thrust,to push推,插入", "http://etymon.cn/yingyucigen/2254.html"),
                Word("err(arr)","to wander漫游","http://etymon.cn/yingyucigen/2256.html"),
                Word("voc,vok(vouc,,vow,voic)","to call喊叫,voide声音","http://etymon.cn/yingyucigen/2255.html"),
                Word("rog","to ask询问,要求","http://etymon.cn/yingyucigen/2253.html"),
                Word("lu,lav,lau","to wash冲洗","http://etymon.cn/yingyucigen/2252.html"),
                Word("ject,jac(jet)","to throw投掷,扔","http://etymon.cn/yingyucigen/2251.html"),
                Word("tom","to cut切","http://etymon.cn/yingyucigen/2247.html"),
                Word("solv,solu,solut","to loosen松的,解","http://etymon.cn/yingyucigen/2246.html"),
                Word("graph,gram","to write书写","http://etymon.cn/yingyucigen/1063.html"),
                Word("cond","to hide隐藏","http://etymon.cn/yingyucigen/2213.html"),
                Word("vert,vers","to turn转,转向,转移","http://etymon.cn/yingyucigen/2212.html"),
                Word("dic,dict","say,assert,allot说话,断言,分派","http://etymon.cn/yingyucigen/2211.html"),
                Word("und,ound","wave波浪","http://etymon.cn/yingyucigen/2210.html"),
                Word("norm","standard,rule规范,正规,正常,标准","http://etymon.cn/yingyucigen/2209.html"),
                Word("juven","young年轻,年少","http://etymon.cn/yingyucigen/1652.html"),
                Word("tain,ten,tin,tent","hold握,持,守","http://etymon.cn/yingyucigen/2208.html"),
                Word("hom,hum","man,hum,earth,ground人类,地,湿","http://etymon.cn/yingyucigen/2207.html"),
                Word("sat(set)","enough满","http://etymon.cn/yingyucigen/2199.html"),
                Word("sent,sens","to feel感觉","http://etymon.cn/yingyucigen/2198.html"),
                Word("cert","sure确实,确信","http://etymon.cn/yingyucigen/2197.html"),
                Word("pris,prehend,prehens(pren,pregn,priev)","to take,to seize","http://etymon.cn/yingyucigen/2018.html"),
                Word("cent,cant(chant,chans)","to sing,song歌唱","http://etymon.cn/yingyucigen/2194.html"),
                Word("cre(cru),cresc,cret","to grow,to increase生长","http://etymon.cn/yingyucigen/2193.html"),
                Word("bas","lower缩小,降低,减少,bottom底","http://etymon.cn/yingyucigen/2192.html"),
                Word("bas,bat","go,walk走","http://etymon.cn/yingyucigen/2191.html"),
                Word("prob,prov","to test,to try试,to examine试验","http://etymon.cn/yingyucigen/2189.html"),
                Word("scrib,script","to write写","http://etymon.cn/yingyucigen/2188.html"),
                Word("fam,fat,phon","to speak说,论","http://etymon.cn/yingyucigen/2187.html"),
                Word("fa,fabl,fabul","to speak说","http://etymon.cn/yingyucigen/2186.html"),
                Word("ver","true真实","http://etymon.cn/yingyucigen/2185.html"),
                Word("tribut","to give,to pay给予","http://etymon.cn/yingyucigen/2184.html"),
                Word("fess","to say,to talk说","http://etymon.cn/yingyucigen/2183.html"),
                Word("grand","great,large大","http://etymon.cn/yingyucigen/2182.html"),
                Word("spers(spars)","to sprinke,to strew,to scatter散,撒","http://etymon.cn/yingyucigen/2181.html"),
                Word("sever","serious","http://etymon.cn/yingyucigen/2179.html"),
                Word("front","forehead,face前,前面,前部,前额","http://etymon.cn/yingyucigen/2178.html"),
                Word("junct,join(jug)","to join,to bind连接","http://etymon.cn/yingyucigen/2177.html"),
                Word("jud,jur,jus(t)","to judge判断","http://etymon.cn/yingyucigen/2176.html"),
                Word("coast,cost","rib肋骨,side旁边,边","http://etymon.cn/yingyucigen/2175.html"),
                Word("col(cul)","neck脖子","http://etymon.cn/yingyucigen/2174.html"),
                Word("tenu","thin细薄","http://etymon.cn/yingyucigen/2173.html"),
                Word("pon,pound,pos(it)","to put放置","http://etymon.cn/yingyucigen/2167.html"),
                Word("pos,post","to put,to place放,置","http://etymon.cn/yingyucigen/2166.html"),
                Word("tri,trit","to rub擦","http://etymon.cn/yingyucigen/2165.html"),
                Word("fin","end末尾,limit界限","http://etymon.cn/yingyucigen/2164.html"),
                Word("umbr","shade,to shadow阴影","http://etymon.cn/yingyucigen/2163.html"),
                Word("bys","end,bottom","http://etymon.cn/yingyucigen/2161.html"),
                Word("onym(onom)","name名字","http://etymon.cn/yingyucigen/2160.html"),
                Word("dot,don(dow,dos),dat(dit)","to give给","http://etymon.cn/yingyucigen/2159.html"),
                Word("path(o),pat(i),pass(i),pathy","to feel感受,to suffer受苦的","http://etymon.cn/yingyucigen/2157.html"),
                Word("(a)esthet,(a)esthes","to feel","http://etymon.cn/yingyucigen/2143.html"),
                Word("troph","to nourish","http://etymon.cn/yingyucigen/2142.html"),
                Word("mne,mnes,mem(or)","to remember记住的",""),
                Word("morph","form形","http://etymon.cn/yingyucigen/2140.html"),
                Word("press","to press压","http://etymon.cn/yingyucigen/2136.html"),
                Word("ple(t),plet,pli,ply,plen(i)","full,to fill装满(的)","http://etymon.cn/yingyucigen/2135.html"),
                Word("pact","to fasten系紧,to agree同意","http://etymon.cn/yingyucigen/2134.html"),
                Word("ment","mind心智,to think想","http://etymon.cn/yingyucigen/2133.html"),
                Word("sol","alone/single,whole/entire单独的","http://etymon.cn/yingyucigen/2132.html"),
                Word("sol","sun太阳","http://etymon.cn/yingyucigen/2131.html"),
                Word("via(vi),vey,voy,way","way,road道路","http://etymon.cn/yingyucigen/2130.html"),
                Word("cis(cas,chis),cide","to cut切","http://etymon.cn/yingyucigen/2129.html"),
                Word("bat","to strike,to beat打","http://etymon.cn/yingyucigen/2127.html"),
                Word("ag,act,ig","to drive驱使,to do做","http://etymon.cn/yingyucigen/2126.html"),
                Word("tend,tens,tent","to stretch伸","http://etymon.cn/yingyucigen/2124.html"),
                Word("punct,pung(punc,pounc,polgn,pon,point)","to prick刺","http://etymon.cn/yingyucigen/2113.html"),
                Word("clud,clus(clos,clois,claus,clot)","to shut关闭","http://etymon.cn/yingyucigen/2095.html"),
                Word("mot,mov,mob","to move运动","http://etymon.cn/yingyucigen/2074.html"),
                Word("sequ,secut,su","to follow跟随","http://etymon.cn/yingyucigen/2072.html"),
                Word("strain,strict,string,stress(strang)","to draw,tight拉紧","http://etymon.cn/yingyucigen/2070.html"),
                Word("pto","to fall","http://etymon.cn/yingyucigen/1052.html"),
                Word("cid,cad,cas","to fall落下,降临","http://etymon.cn/yingyucigen/2071.html"),
                Word("ger,gest(gist)","to carry运,载","http://etymon.cn/yingyucigen/2037.html"),
                Word("labor","to work工作","http://etymon.cn/yingyucigen/2034.html"),
                Word("vict,vinc","to conquer征服","http://etymon.cn/yingyucigen/2033.html"),
                Word("tempor","time,age,season","http://etymon.cn/yingyucigen/2017.html"),
                Word("solid(sold)","firm,whole","http://etymon.cn/yingyucigen/2016.html"),
                Word("lat","to carry带来,to bear搬运,担负","http://etymon.cn/yingyucigen/2012.html"),
                Word("fer","to carry拿,to bring带来,to bear负担","http://etymon.cn/yingyucigen/2015.html"),
                Word("coc,coct","to cook,to mature","http://etymon.cn/yingyucigen/2014.html"),
                Word("miser","to pity,wretched","http://etymon.cn/yingyucigen/2013.html"),
                Word("alesc(esc,alit,olesc)","becoming","http://etymon.cn/yingyucigen/2011.html"),
                Word("secr,sacr,sanct(sacer,saint)","holy,sacred神圣的","http://etymon.cn/yingyucigen/2010.html"),
                Word("flagr,flam","to burn燃烧,flame火焰","http://etymon.cn/yingyucigen/2009.html"),
                Word("dol","to grieve","http://etymon.cn/yingyucigen/2008.html"),
                Word("plac(plais),pleas","to please,to soothe,peace","http://etymon.cn/yingyucigen/2005.html"),
                Word("rod,ros","to gnaw咬,啮","http://etymon.cn/yingyucigen/2004.html"),
                Word("rob","strong,strength","http://etymon.cn/yingyucigen/2003.html"),
                Word("tang,tact,ting(tig,tag)","to touch","http://etymon.cn/yingyucigen/2002.html"),
                Word("stern(stren)","rigid严格的,僵硬的,规则,方法","http://etymon.cn/yingyucigen/2001.html"),
                Word("viv,vit","to live,life活,生活","http://etymon.cn/yingyucigen/1998.html"),
                Word("sign","mark,sign","http://etymon.cn/yingyucigen/2000.html"),
                Word("summ","highest,total,sum","http://etymon.cn/yingyucigen/1999.html"),
                Word("mens","to measure","http://etymon.cn/yingyucigen/1997.html"),
                Word("tum","to swell肿胀","http://etymon.cn/yingyucigen/1994.html"),
                Word("pict(pig)","to paint","http://etymon.cn/yingyucigen/1996.html"),
                Word("volv,volu,volut","to roll,to turn","http://etymon.cn/yingyucigen/1995.html"),
                Word("tra,tract(treat)","to draw拉拽","http://etymon.cn/yingyucigen/1993.html"),
                Word("act,ag","to do,to drive做,驱使","http://etymon.cn/yingyucigen/1988.html"),
                Word("test","witness证据","http://etymon.cn/yingyucigen/1981.html"),
                Word("grad,gress(gred)","to go,to walk走","http://etymon.cn/yingyucigen/1980.html"),
                Word("plor","to weep","http://etymon.cn/yingyucigen/1979.html"),
                Word("vac(vas)","empty空","http://etymon.cn/yingyucigen/1978.html"),
                Word("terr","to frighten使惊吓","http://etymon.cn/yingyucigen/1974.html"),
                Word("terr","earth地","http://etymon.cn/yingyucigen/1973.html"),
                Word("mol,moll","to grind,grain,burden,heap,moll","http://etymon.cn/yingyucigen/1970.html"),
                Word("crep","to rattle","http://etymon.cn/yingyucigen/1969.html"),
                Word("void","empty","http://etymon.cn/yingyucigen/1968.html"),
                Word("vid,vis","to look,to see","http://etymon.cn/yingyucigen/1967.html"),
                Word("rid,ris","to laugh笑","http://etymon.cn/yingyucigen/1966.html"),
                Word("men(mean)","to lead","http://etymon.cn/yingyucigen/1965.html"),
                Word("fac,front","face面部,正面,forehead前额","http://etymon.cn/yingyucigen/1964.html"),
                Word("lin,lign","line","http://etymon.cn/yingyucigen/1963.html"),
                Word("lec(let,lic,lig)","to entice","http://etymon.cn/yingyucigen/1962.html"),
                Word("pred,preda","to plunder掠夺,to prey掠食","http://etymon.cn/yingyucigen/1961.html"),
                Word("prec","to pray祈祷","http://etymon.cn/yingyucigen/1960.html"),
                Word("linqu(lic,lict)","to leave","http://etymon.cn/yingyucigen/1959.html"),
                Word("est,ess,ent","to be存在","http://etymon.cn/yingyucigen/1949.html"),
                Word("cret,cern(creet,cre)","to observe观察,to sift筛选","http://etymon.cn/yingyucigen/1948.html"),
                Word("cred(creed,cre)","to believe,to trust相信","http://etymon.cn/yingyucigen/1946.html"),
                Word("min(men)","to hang,to project突出","http://etymon.cn/yingyucigen/1938.html"),
                Word("sect","to cut","http://etymon.cn/yingyucigen/1937.html"),
                Word("arm","weapon","http://etymon.cn/yingyucigen/1933.html"),
                Word("fid(fi,fy,feder,feal)","to trust","http://etymon.cn/yingyucigen/1928.html"),
                Word("vulg(mulg)","people","http://etymon.cn/yingyucigen/1927.html"),
                Word("verg","to turn,to bend倾向,倾斜","http://etymon.cn/yingyucigen/1926.html"),
                Word("put","to think","http://etymon.cn/yingyucigen/1924.html"),
                Word("clin(cli)","to bend弯曲","http://etymon.cn/yingyucigen/1919.html"),
                Word("cur,curs(cor,cour,cours,coars)","to run","http://etymon.cn/yingyucigen/1914.html"),
                Word("sembl","same,equal","http://etymon.cn/yingyucigen/1913.html"),
                Word("tort(tor)","to twist卷缩","http://etymon.cn/yingyucigen/1912.html"),
                Word("semin(semen)","seed种子","http://etymon.cn/yingyucigen/1911.html"),
                Word("quist,quest,quir,quer(quist)","to ask,to seek","http://etymon.cn/yingyucigen/1910.html"),
                Word("bol,bl,bal","to throw","http://etymon.cn/yingyucigen/1909.html"),
                Word("pass","to stride,to step","http://etymon.cn/yingyucigen/1908.html"),
                Word("pot(pow,poss)","powerful,capable of","http://etymon.cn/yingyucigen/1907.html"),
                Word("croch(croach,crouch,crutch,crook)","hook,to bend","http://etymon.cn/yingyucigen/1906.html"),
                Word("body","body","http://etymon.cn/yingyucigen/1905.html"),
                Word("bar","bar横木","http://etymon.cn/yingyucigen/1904.html"),
                Word("am(em,im,m)","to love,friendly","http://etymon.cn/yingyucigen/1903.html"),
                Word("tail","to cut","http://etymon.cn/yingyucigen/1902.html"),
                Word("light","light","http://etymon.cn/yingyucigen/1901.html"),
                Word("gross","large,thick","http://etymon.cn/yingyucigen/1900.html"),
                Word("bell","beautiful,war","http://etymon.cn/yingyucigen/1899.html"),
                Word("com","revel,hair,sleep","http://etymon.cn/yingyucigen/1898.html"),
                Word("cumb,cub","to lean,to lie","http://etymon.cn/yingyucigen/1897.html"),
                Word("clav","key","http://etymon.cn/yingyucigen/1896.html"),
                Word("per(pir,par)","to try out,to risk","http://etymon.cn/yingyucigen/1895.html"),
                Word("numer","number,to count","http://etymon.cn/yingyucigen/1894.html"),
                Word("alt(haut)","high","http://etymon.cn/yingyucigen/1893.html"),
                Word("radic(radis)","root","http://etymon.cn/yingyucigen/1892.html"),
                Word("lip","to leave","http://etymon.cn/yingyucigen/1891.html"),
                Word("stinct,sting,stig,sti","to prick,to bind","http://etymon.cn/yingyucigen/1890.html"),
                Word("long","long","http://etymon.cn/yingyucigen/1889.html"),
                Word("orb","circle,track","http://etymon.cn/yingyucigen/1888.html"),
                Word("hod(od)","way,road","http://etymon.cn/yingyucigen/1887.html"),
                Word("manu(man)","hand手","http://etymon.cn/yingyucigen/1886.html"),
                Word("termin,term","end,limit,boundry","http://etymon.cn/yingyucigen/1885.html"),
                Word("tol","to raise,to support","http://etymon.cn/yingyucigen/1882.html"),
                Word("van(vain),vac,void","empty","http://etymon.cn/yingyucigen/1881.html"),
                Word("rud","crude,raw","http://etymon.cn/yingyucigen/1880.html"),
                Word("pi","holy","http://etymon.cn/yingyucigen/1876.html"),
                Word("hort","to urge","http://etymon.cn/yingyucigen/1875.html"),
                Word("hilar","merry","http://etymon.cn/yingyucigen/1874.html"),
                Word("figur","to shape形成,figure形状","http://etymon.cn/yingyucigen/1873.html"),
                Word("fig","to form","http://etymon.cn/yingyucigen/1872.html"),
                Word("bull","to boil,seal","http://etymon.cn/yingyucigen/1871.html"),
                Word("mers,merg","to dip,to plunge","http://etymon.cn/yingyucigen/1867.html"),
                Word("fet","productive","http://etymon.cn/yingyucigen/1866.html"),
                Word("nerv,neur,neuro","nerve神经","http://etymon.cn/yingyucigen/1865.html"),
                Word("mend","to order","http://etymon.cn/yingyucigen/1864.html"),
                Word("man(mn,main)","to flow,to stay","http://etymon.cn/yingyucigen/1863.html"),
                Word("nov","new新的","http://etymon.cn/yingyucigen/1862.html"),
                Word("it(i)","to go走","http://etymon.cn/yingyucigen/1861.html"),
                Word("tim(tem)","to fear","http://etymon.cn/yingyucigen/1860.html"),
                Word("part","part部分,to part分开","http://etymon.cn/yingyucigen/1859.html"),
                Word("flat","to blow吹","http://etymon.cn/yingyucigen/1858.html"),
                Word("order,ord,ordin(ordain)","ord,ordin","http://etymon.cn/yingyucigen/1857.html"),
                Word("pun,pen(poen)","to punish,pen","http://etymon.cn/yingyucigen/1854.html"),
                Word("still","to drop","http://etymon.cn/yingyucigen/1853.html"),
                Word("mort,mors,mor","death死","http://etymon.cn/yingyucigen/1852.html"),
                Word("ciner","ashes","http://etymon.cn/yingyucigen/1851.html"),
                Word("pover(pauper)","poor","http://etymon.cn/yingyucigen/1850.html"),
                Word("cit","to call,to arouse","http://etymon.cn/yingyucigen/1849.html"),
                Word("trep,trem","to fear","http://etymon.cn/yingyucigen/1848.html"),
                Word("sinu","curve,hollow","http://etymon.cn/yingyucigen/1847.html"),
                Word("bib(bev)","to drink","http://etymon.cn/yingyucigen/1846.html"),
                Word("var(i)","change","http://etymon.cn/yingyucigen/1844.html"),
                Word("damn(demn,dam)","ourse,harm","http://etymon.cn/yingyucigen/1843.html"),
                Word("pet(pit,peat)","to rush,to seek,to strive","http://etymon.cn/yingyucigen/1842.html"),
                Word("fall,fals","to err,to deceive","http://etymon.cn/yingyucigen/1840.html"),
                Word("noc(nox,nic,nec)","to harm伤害","http://etymon.cn/yingyucigen/1839.html"),
                Word("tegr","to touch","http://etymon.cn/yingyucigen/1838.html"),
                Word("vet","old","http://etymon.cn/yingyucigen/1837.html"),
                Word("mut","to change","http://etymon.cn/yingyucigen/1836.html"),
                Word("vuln(vult)","wound","http://etymon.cn/yingyucigen/1835.html"),
                Word("pugn","to fight","http://etymon.cn/yingyucigen/1834.html"),
                Word("avi(av)","bird","http://etymon.cn/yingyucigen/1833.html"),
                Word("anim","life,mind,breath","http://etymon.cn/yingyucigen/1832.html"),
                Word("firm","strong","http://etymon.cn/yingyucigen/1831.html"),
                Word("calc(culc)","to tread","http://etymon.cn/yingyucigen/1830.html"),
                Word("surg(e),srect,surrect","to rise(立起)","http://etymon.cn/yingyucigen/1829.html"),
                Word("scrut","to examine","http://etymon.cn/yingyucigen/1828.html"),
                Word("veh,vect(veigh,vex)","to carry","http://etymon.cn/yingyucigen/1827.html"),
                Word("turb","to agitate","http://etymon.cn/yingyucigen/1825.html"),
                Word("pecu","money","http://etymon.cn/yingyucigen/1824.html"),
                Word("mur","wall","http://etymon.cn/yingyucigen/1821.html"),
                Word("macul","stain,spot","http://etymon.cn/yingyucigen/1820.html"),
                Word("luct","to struggle","http://etymon.cn/yingyucigen/1819.html"),
                Word("rupt","to break","http://etymon.cn/yingyucigen/1818.html"),
                Word("medi","middle中间","http://etymon.cn/yingyucigen/1817.html"),
                Word("rect,rig"," straight直的,right公正的,正当的","http://etymon.cn/yingyucigen/1814.html"),
                Word("liter","letter文字","http://etymon.cn/yingyucigen/1813.html"),
                Word("cel(cul,ceal)","cul,ceal","http://etymon.cn/yingyucigen/1811.html"),
                Word("dur","to last持续","http://etymon.cn/yingyucigen/1810.html"),
                Word("scen","to set","http://etymon.cn/yingyucigen/1809.html"),
                Word("sit","food,grain,to sir","http://www.etymon.cn/yingyucigen/1806.html"),
                Word("dox, dogma","opinion意见","http://www.etymon.cn/yingyucigen/1805.html"),
                Word("od","song","http://www.etymon.cn/yingyucigen/1804.html"),
                Word("meter(metr)","measure,metr测量","http://www.etymon.cn/yingyucigen/1803.html"),
                Word("phras,pha,phe,phu","to say,to speek","http://www.etymon.cn/yingyucigen/1801.html"),
                Word("jur","to swear,law","http://www.etymon.cn/yingyucigen/1798.html"),
                Word("vad,vas(wad)","to go","http://www.etymon.cn/yingyucigen/1787.html"),
                Word("mea(me)","to pass","http://www.etymon.cn/yingyucigen/1786.html"),
                Word("ann,enn","year","http://www.etymon.cn/yingyucigen/1785.html"),
                Word("funct","to perform","http://www.etymon.cn/yingyucigen/1784.html"),
                Word("mat","ripe","http://www.etymon.cn/yingyucigen/1783.html"),
                Word("cau","to take care","http://www.etymon.cn/yingyucigen/1782.html"),
                Word("ambul(ambl)","to walk","http://www.etymon.cn/yingyucigen/1781.html"),
                Word("domin","master,lord","http://www.etymon.cn/yingyucigen/1780.html"),
                Word("poster","coming after","http://www.etymon.cn/yingyucigen/1749.html"),
                Word("text","to weave","http://www.etymon.cn/yingyucigen/1748.html"),
                Word("med","to heal,to attend to","http://www.etymon.cn/yingyucigen/1747.html"),
                Word("mon(min)","to warn,to advise,to remind","http://www.etymon.cn/yingyucigen/1724.html"),
                Word("sci","to know","http://www.etymon.cn/yingyucigen/1723.html"),
                Word("sag","to perceive","http://www.etymon.cn/yingyucigen/1722.html"),
                Word("cur","to take care","http://www.etymon.cn/yingyucigen/1721.html"),
                Word("mont,mount","hill,to rise","http://www.etymon.cn/yingyucigen/1720.html"),
                Word("fus,fut,fund,found","to pour","http://www.etymon.cn/yingyucigen/1692.html"),
                Word("al,ol,ul","to nourish滋养","http://www.etymon.cn/yingyucigen/1691.html"),
                Word("teg,tect","to hide,to cover","http://www.etymon.cn/yingyucigen/1690.html"),
                Word("cliv","to bend","http://www.etymon.cn/yingyucigen/1689.html"),
                Word("burs"," bag,sack,purse","http://www.etymon.cn/yingyucigen/1688.html"),
                Word("fort,forc","strong","http://www.etymon.cn/yingyucigen/1687.html"),
                Word("hab(hib)","to live,to have,to hold","http://www.etymon.cn/yingyucigen/1685.html"),
                Word("len","soft","http://www.etymon.cn/yingyucigen/1651.html"),
                Word("vil","cheap","http://www.etymon.cn/yingyucigen/1650.html"),
                Word("eng","to deny","http://www.etymon.cn/yingyucigen/1649.html"),
                Word("nounc,nunci","to say,to report","http://www.etymon.cn/yingyucigen/1648.html"),
                Word("ac(tic)","silent","http://www.etymon.cn/yingyucigen/1647.html"),
                Word("scind,scis","to cut","http://www.etymon.cn/yingyucigen/1646.html"),
                Word("dub(doub)","uncertain","http://www.etymon.cn/yingyucigen/1645.html"),
                Word("pud","ashamed","http://www.etymon.cn/yingyucigen/1644.html"),
                Word("monstr","to show","http://www.etymon.cn/yingyucigen/1643.html"),
                Word("trench","to cut","http://www.etymon.cn/yingyucigen/1512.html"),
                Word("fulg","to shine","http://www.etymon.cn/yingyucigen/1511.html"),
                Word("ol,od","smell","http://www.etymon.cn/yingyucigen/1510.html"),
                Word("splend","to shine发光,照耀","http://www.etymon.cn/yingyucigen/1509.html"),
                Word("fract,frag(fra,fring)","to break打破","http://www.etymon.cn/yingyucigen/1508.html"),
                Word("cinct","to bind,to gird","http://www.etymon.cn/yingyucigen/1440.html"),
                Word("rap,rav(rep)"," to take,to snatch攫取","http://www.etymon.cn/yingyucigen/1439.html"),
                Word("cili ","eyelid","http://www.etymon.cn/yingyucigen/1334.html"),
                Word("plu","more","http://www.etymon.cn/yingyucigen/1333.html"),
                Word("mit,miss(mis,mess) ","to send送，to throw投,掷","http://www.etymon.cn/yingyucigen/1332.html"),
                Word("form","form形状，to form形成","http://www.etymon.cn/yingyucigen/1331.html"),
                Word("scend,scent,scens,scan","to climb","http://www.etymon.cn/yingyucigen/1330.html"),
                Word("vest","to dress","http://www.etymon.cn/yingyucigen/1132.html"),
                Word("bond，band","to bind捆绑","http://www.etymon.cn/yingyucigen/1130.html"),
                Word("salv,sav","safe","http://www.etymon.cn/yingyucigen/1129.html"),
                Word("pil","hair","http://www.etymon.cn/yingyucigen/1127.html"),
                Word("verb","word字,词","http://www.etymon.cn/yingyucigen/1126.html"),
                Word("mir","to wonder惊讶，to behold看见","http://www.etymon.cn/yingyucigen/1125.html"),
                Word("prox,prop","near","http://www.etymon.cn/yingyucigen/1123.html"),
                Word("leth","death","http://www.etymon.cn/yingyucigen/1120.html"),
                Word("hier","holy","http://www.etymon.cn/yingyucigen/1119.html"),
                Word("propr,proper,propri","proper适当的，one's own自己","http://www.etymon.cn/yingyucigen/1118.html"),
                Word("log,loqu,locut","to speek说话","http://www.etymon.cn/yingyucigen/1117.html"),
                Word("aud(ed,eis)","to hear","http://www.etymon.cn/yingyucigen/1116.html"),
                Word("doc","to teach教导","http://www.etymon.cn/yingyucigen/1115.html"),
                Word("cuss","to strike,to shake","http://www.etymon.cn/yingyucigen/1114.html"),
                Word("let,liv","lime","http://www.etymon.cn/yingyucigen/1113.html"),
                Word("pecc","sin","http://www.etymon.cn/yingyucigen/1112.html"),
                Word("palp","to touch","http://www.etymon.cn/yingyucigen/1111.html"),
                Word("culp","fault,to blame","http://www.etymon.cn/yingyucigen/1110.html"),
                Word("cens","to assess","http://www.etymon.cn/yingyucigen/1109.html"),
                Word("domit","to tame","http://www.etymon.cn/yingyucigen/1108.html"),
                Word("cel","sky,heaven","http://www.etymon.cn/yingyucigen/1105.html"),
                Word("glob","sphere","http://www.etymon.cn/yingyucigen/1104.html"),
                Word("mar","war","http://www.etymon.cn/yingyucigen/1103.html"),
                Word("op,opt,,opto,ophthalm","eye眼睛,sight视力","http://www.etymon.cn/yingyucigen/1101.html"),
                Word("patr(pater)","father,country","http://www.etymon.cn/yingyucigen/1100.html"),
                Word("rus,rur"," country乡村","http://www.etymon.cn/yingyucigen/1097.html"),
                Word("cruc (cruis)","cross十字,交叉","http://www.etymon.cn/yingyucigen/1096.html"),
                Word("coloss (colis)","great","http://www.etymon.cn/yingyucigen/1095.html"),
                Word("hemer","day","http://www.etymon.cn/yingyucigen/1094.html"),
                Word("noct,nox","night夜晚","http://www.etymon.cn/yingyucigen/1093.html"),
                Word("nomin,nomen","name名字","http://www.etymon.cn/yingyucigen/1092.html"),
                Word("ban","prohibition,control","http://www.etymon.cn/yingyucigen/1091.html"),
                Word("prim(prem,prin,pri)","first第一","http://www.etymon.cn/yingyucigen/1090.html"),
                Word("dig","to need ,to lack","http://www.etymon.cn/yingyucigen/1083.html"),
                Word("vig,veg","to live,lively快活的,有生气的","http://www.etymon.cn/yingyucigen/1081.html"),
                Word("ferv"," to boil沸腾","http://www.etymon.cn/yingyucigen/1080.html"),
                Word("dorm","to sleep睡眠","http://www.etymon.cn/yingyucigen/1079.html"),
                Word("milit","soldier士兵，to fight战斗","http://www.etymon.cn/yingyucigen/1078.html"),
                Word("vag(vaga)"," to wander流浪,漂泊","http://www.etymon.cn/yingyucigen/1077.html"),
                Word("dulg"," to yield","http://www.etymon.cn/yingyucigen/1076.html"),
                Word("chal","warm,ardent","http://www.etymon.cn/yingyucigen/1075.html"),
                Word("somn","to sleep睡眠","http://www.etymon.cn/yingyucigen/1073.html"),
                Word("mun(muni)","duty,function,gift,service","http://www.etymon.cn/yingyucigen/1071.html"),
                Word("comit","to accompany","http://www.etymon.cn/yingyucigen/1070.html"),
                Word("mord,mors","to bite","http://www.etymon.cn/yingyucigen/1069.html"),
                Word("clar(clair)","clear","http://www.etymon.cn/yingyucigen/1068.html"),
                Word("merc","to trade贸易，reward报酬","http://www.etymon.cn/yingyucigen/1067.html"),
                Word("aug,auct(aux)","to increase增加,to make to grow使产","http://www.etymon.cn/yingyucigen/1066.html"),
                Word("mand,mend","to order命令,to entrust委托","http://www.etymon.cn/yingyucigen/1065.html"),
                Word("mim","to imitate","http://www.etymon.cn/yingyucigen/1064.html"),
                Word("caust,caut","to brun","http://www.etymon.cn/yingyucigen/1062.html"),
                Word("crat,cracy"," to govern,to rule,government","http://www.etymon.cn/yingyucigen/1061.html"),
                Word("thet,thes(thec,them)","to place,to put置放","http://www.etymon.cn/yingyucigen/1060.html"),
                Word("ax","axis","http://www.etymon.cn/yingyucigen/1059.html"),
                Word("polit(polic,polis) ","city,state","http://www.etymon.cn/yingyucigen/1058.html"),
                Word("egyr","to bring together","http://www.etymon.cn/yingyucigen/1057.html"),
                Word("narc","numbness,stupor","http://www.etymon.cn/yingyucigen/1054.html"),
                Word("prag","prag;pract = to do,business","http://www.etymon.cn/yingyucigen/1053.html"),
                Word("not","to know，to mark","http://www.etymon.cn/yingyucigen/1051.html"),
                Word("caval (chival)","hosre","http://www.etymon.cn/yingyucigen/1048.html"),
                Word("magn,maj,max","great伟大的,壮大的","http://www.etymon.cn/yingyucigen/1047.html"),
                Word("grat (grac)"," thankful,pleasing喜好","http://www.etymon.cn/yingyucigen/1046.html"),
                Word("merit","to deserve,to earn","http://www.etymon.cn/yingyucigen/1045.html"),
                Word("phon","sound声音,phe = to speak 说话","http://www.etymon.cn/yingyucigen/1044.html"),
                Word("lumin (lun)","light","http://www.etymon.cn/yingyucigen/1043.html"),
                Word("phan (phen,fan) "," to show,to appear","http://www.etymon.cn/yingyucigen/1042.html"),
                Word("mell,mel(mil,mol,mar)","honey","http://www.etymon.cn/yingyucigen/1041.html"),
                Word("popul,publ","people人","http://www.etymon.cn/yingyucigen/1015.html"),
                Word("migr","to remove移动,to wander漂泊","http://www.etymon.cn/yingyucigen/1014.html"),
                Word("ultim","end,last最后的","http://www.etymon.cn/yingyucigen/1012.html"),
                Word("orn ","to decorate装饰，to furnish装备","http://www.etymon.cn/yingyucigen/1012.html"),
                Word("scan,scend,scal","to climb登,爬","http://www.etymon.cn/yingyucigen/1011.html"),
                Word("scal","ladder","http://www.etymon.cn/yingyucigen/1011.html"),
                Word("oner","burden","http://www.etymon.cn/yingyucigen/1008.html"),
                Word("insul(isol)","island受岛屿","http://www.etymon.cn/yingyucigen/1007.html"),
                Word("stip","to press together","http://www.etymon.cn/yingyucigen/1006.html"),
                Word("cast","to throw 投掷","http://www.etymon.cn/yingyucigen/1005.html"),
                Word("cast,cest,chast","pure纯洁","http://www.etymon.cn/yingyucigen/1004.html"),
                Word("pat","to walk","http://www.etymon.cn/yingyucigen/955.html"),
                Word("crastin","tomorrow","http://www.etymon.cn/yingyucigen/954.html"),
                Word("flig","to drive","http://www.etymon.cn/yingyucigen/953.html"),
                Word("art","skill技巧，art技术","http://www.etymon.cn/yingyucigen/952.html"),
                Word("acerb","bitter,harsh","http://www.etymon.cn/yingyucigen/846.html"),
                Word("bil","strong","http://www.etymon.cn/yingyucigen/845.html"),
                Word("fusc","dark","http://www.etymon.cn/yingyucigen/844.html"),
                Word("just,juris","law法律，right正义","http://www.etymon.cn/yingyucigen/148.html"),
                Word("varic","varic","http://www.etymon.cn/yingyucigen/1013.html")
        )

        fun findByWord(keyword: CharSequence?): ArrayList<Word> {
            val result = ArrayList<Word>()
            for (i in instances) if (i.word.contains(keyword!!)) result.add(i)
            return result
        }

        fun findByTranslate(keyword: CharSequence?): ArrayList<Word> {
            val result = ArrayList<Word>()
            for (i in instances) if (i.translate.contains(keyword!!)) result.add(i)
            return result
        }

        fun randomWords(count: Int): ArrayList<Word> {
            val result = ArrayList<Word>()
            val temp = instances.shuffled()
            for (i in (0 until count))
                result.add(temp.get(i))
            return result
        }
    }
}